context('Test the basic skeleton pipeline')
test_that('om..echo can be built', {
  module_path <- module_skeleton(program_name = 'echo', flpth = getwd())
  on.exit(unlink(x = module_path, recursive = TRUE, force = TRUE))
  expect_true(module_check(flpth = module_path))
  expect_true(inherits(module_identities(flpth = module_path), 'identities'))
  expect_true(module_build(flpth = module_path, tag = 'latest'))
  expect_true(module_test(flpth = module_path))
  expect_true(outsider::module_uninstall('om..echo'))
})
